const products = [
  { id:'p1', name:'晨光濾掛咖啡', desc:'衣索比亞日曬｜花香與莓果調', price:420, emoji:'☕', tag:'本週人氣' },
  { id:'p2', name:'島嶼果醬組', desc:'季節水果手工熬煮｜三入禮盒', price:680, emoji:'🍓', tag:'限量 12 組' },
  { id:'p3', name:'日常棉麻提袋', desc:'厚磅帆布｜內袋設計｜米白色', price:390, emoji:'👜', tag:'新品' },
];
const state = { view:'shop', cart:JSON.parse(localStorage.getItem('sale_cart')||'[]'), user:JSON.parse(localStorage.getItem('sale_user')||'null'), orders:JSON.parse(localStorage.getItem('sale_orders')||'[]'), modal:null, toast:'' };
const money = n => `NT$ ${n.toLocaleString()}`;
const save = () => { localStorage.setItem('sale_cart',JSON.stringify(state.cart)); localStorage.setItem('sale_user',JSON.stringify(state.user)); localStorage.setItem('sale_orders',JSON.stringify(state.orders)); };
function render(){ document.querySelector('#app').innerHTML = `<div class="shell">${nav()}${state.view==='shop'?shop():state.view==='orders'?orders():admin()}${footer()}</div>${state.modal?modal():''}${state.toast?`<div class="toast">${state.toast}</div>`:''}`; bind(); }
function nav(){return `<header class="nav"><button class="brand" data-view="shop"><span class="mark">✦</span><span>NewShop日本連線代購 <small style="display:block;color:var(--muted);font-weight:500;font-size:10px;letter-spacing:.18em">JAPAN SELECT SHOP</small></span></button><nav class="navlinks"><button class="${state.view==='shop'?'active':''}" data-view="shop">買東西</button><button class="${state.view==='orders'?'active':''}" data-view="orders">我的訂單</button><button class="${state.view==='admin'?'active':''}" data-view="admin">店主後台</button><button class="cart-btn" data-action="cart">購物袋 <span class="badge">${state.cart.reduce((a,b)=>a+b.qty,0)}</span></button></nav></header>`}
function shop(){return `<main><section class="hero"><div class="hero-copy"><span class="eyebrow">熟客限定・每週更新</span><h1>把喜歡的<br/><em style="color:var(--coral)">帶回日常。</em></h1><p>一個給熟客的小小訂購站。選好商品、留下聯絡方式，我們會在備貨完成後通知你。</p><button class="btn btn-primary" data-scroll="products">開始選購 ↓</button></div><div class="hero-card"><span class="card-label">THIS WEEK'S PICK / 01</span><div class="card-copy"><h2>小島日常包</h2><p style="opacity:.8;line-height:1.7">咖啡、果醬與一只提袋，剛好成為今天的好心情。</p><button class="btn btn-light" data-add="p1">加入濾掛咖啡</button></div></div></section><section id="products"><div class="section-head"><div><h2>本週選物</h2><p>少量上架，售完就等下週。</p></div><span class="eyebrow">03 ITEMS</span></div><div class="products">${products.map(productCard).join('')}</div></section></main>`}
function productCard(p){return `<article class="product"><div class="product-art"><span class="product-tag">${p.tag}</span>${p.emoji}</div><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="product-bottom"><span class="price">${money(p.price)}</span><button class="btn btn-accent" data-add="${p.id}">加入購物袋</button></div></div></article>`}
function orders(){return `<main class="split"><section class="panel"><span class="eyebrow">MEMBER AREA</span><h2 style="margin-top:10px">${state.user?`${state.user.name||state.user.account} 的訂單`:'登入後查看訂單'}</h2>${state.user?`<p style="color:var(--muted)">${state.user.email}</p><button class="btn btn-primary" data-action="logout">登出</button>`:`<p style="color:var(--muted);line-height:1.8">註冊一個帳號，就能在這裡追蹤每次訂購。</p><button class="btn btn-primary" data-modal="auth">登入／註冊</button>`}</section><section class="panel"><h2>訂單紀錄</h2>${state.orders.length?state.orders.slice().reverse().map(o=>`<div class="order"><div><strong>${o.id}</strong><div style="font-size:13px;color:var(--muted);margin-top:4px">${o.items.map(i=>`${i.name} × ${i.qty}`).join('、')}</div></div><div style="text-align:right"><strong>${money(o.total)}</strong><div class="status">${o.status}</div></div></div>`).join(''):`<div class="empty">目前還沒有訂單<br/><button class="btn btn-accent" data-view="shop" style="margin-top:12px">去逛逛</button></div>`}</section></main>`}
function admin(){let total=state.orders.reduce((a,o)=>a+o.total,0);return `<main class="panel" style="margin:30px 0 80px"><div class="section-head"><div><span class="eyebrow">OWNER CONSOLE</span><h2 style="margin-top:10px">訂單總覽</h2></div><button class="btn btn-primary" data-action="export">下載 Excel 報表</button></div><div class="admin-stats"><div class="stat"><small>總訂單</small><strong>${state.orders.length}</strong></div><div class="stat"><small>待處理</small><strong>${state.orders.filter(o=>o.status==='待確認').length}</strong></div><div class="stat"><small>訂單總額</small><strong>${money(total)}</strong></div></div>${state.orders.length?`<div style="overflow:auto"><table style="width:100%;border-collapse:collapse;text-align:left"><thead><tr style="color:var(--muted);font-size:13px"><th style="padding:10px">訂單編號</th><th>客戶</th><th>品項</th><th>金額</th><th>狀態</th></tr></thead><tbody>${state.orders.slice().reverse().map(o=>`<tr style="border-top:1px solid var(--line)"><td style="padding:14px 10px">${o.id}</td><td>${o.customer}</td><td>${o.items.map(i=>`${i.name} × ${i.qty}`).join('<br/>')}</td><td>${money(o.total)}</td><td><span class="status">${o.status}</span></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">還沒有訂單。先用前台下單，這裡就會出現資料。</div>`}</main>`}
function footer(){return `<footer>NewShop日本連線代購 <span style="float:right">第一版試營運・資料保存在本機</span></footer>`}
function modal(){if(state.modal==='cart') return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><span class="eyebrow">YOUR BAG</span><h2>購物袋</h2></div><button class="close" data-action="close">×</button></div>${state.cart.length?`${state.cart.map(i=>`<div class="order"><div><strong>${i.name}</strong><div style="font-size:13px;color:var(--muted)">${money(i.price)} × ${i.qty}</div></div><button class="btn" data-remove="${i.id}" style="background:#f0eee6">移除</button></div>`).join('')}<div style="display:flex;justify-content:space-between;margin:20px 0;font-size:18px"><strong>合計</strong><strong>${money(state.cart.reduce((a,i)=>a+i.price*i.qty,0))}</strong></div><button class="btn btn-primary" style="width:100%" data-modal="checkout">前往結帳</button>`:`<div class="empty">購物袋還是空的</div>`}</div></div>`;if(state.modal==='auth')return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><span class="eyebrow">WELCOME BACK</span><h2>會員登入／註冊</h2></div><button class="close" data-action="close">×</button></div><div class="field"><label>信箱</label><input id="email" type="email" placeholder="you@example.com" /></div><div class="field"><label>帳號</label><input id="account" placeholder="你的暱稱" /></div><div class="field"><label>密碼</label><input id="password" type="password" placeholder="至少 6 個字元" /></div><button class="btn btn-primary" style="width:100%" data-action="login">登入／建立帳號</button><p style="font-size:12px;color:var(--muted);margin:14px 0 0">展示版不會送出資料，僅保存在這台裝置。</p></div></div>`;if(state.modal==='checkout')return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><span class="eyebrow">CHECKOUT</span><h2>確認訂單</h2></div><button class="close" data-action="close">×</button></div><div class="field"><label>收件人</label><input id="customer" placeholder="請輸入姓名" /></div><div class="field"><label>聯絡電話</label><input id="phone" placeholder="09xx-xxx-xxx" /></div><div class="field"><label>取貨方式</label><select id="delivery"><option>面交取貨</option><option>宅配到府</option></select></div><button class="btn btn-accent" style="width:100%" data-action="checkout">送出訂單・${money(state.cart.reduce((a,i)=>a+i.price*i.qty,0))}</button></div></div>`;}
function toast(message){state.toast=message;render();setTimeout(()=>{state.toast='';render()},1800)}
function add(id){const p=products.find(x=>x.id===id), item=state.cart.find(x=>x.id===id);if(item)item.qty++;else state.cart.push({...p,qty:1});save();toast(`${p.name} 已加入購物袋`)}
function exportCsv(){const rows=[['訂單編號','日期','客戶','電話','品項','數量','金額','狀態'],...state.orders.flatMap(o=>o.items.map(i=>[o.id,o.date,o.customer,o.phone,i.name,i.qty,i.price*i.qty,o.status]))];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`NewShop日本連線代購訂單-${new Date().toISOString().slice(0,10)}.csv`;a.click();}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));document.querySelector('[data-scroll]')?.addEventListener('click',()=>document.querySelector('#products').scrollIntoView({behavior:'smooth'}));document.querySelector('[data-action="cart"]')?.addEventListener('click',()=>{state.modal='cart';render()});document.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>{state.modal=b.dataset.modal;render()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.cart=state.cart.filter(x=>x.id!==b.dataset.remove);save();render()});document.querySelectorAll('[data-action="close"]').forEach(b=>b.onclick=()=>{state.modal=null;render()});document.querySelector('[data-action="login"]')?.addEventListener('click',()=>{const email=document.querySelector('#email').value.trim(),account=document.querySelector('#account').value.trim();if(!email||!account){toast('請填寫信箱與帳號');return}state.user={email,account,name:account};state.modal=null;save();toast('歡迎加入小島選物');});document.querySelector('[data-action="logout"]')?.addEventListener('click',()=>{state.user=null;save();render()});document.querySelector('[data-action="checkout"]')?.addEventListener('click',()=>{const customer=document.querySelector('#customer').value.trim(),phone=document.querySelector('#phone').value.trim();if(!customer||!phone){toast('請填寫收件人與電話');return}const total=state.cart.reduce((a,i)=>a+i.price*i.qty,0);state.orders.push({id:`IS-${Date.now().toString().slice(-6)}`,date:new Date().toLocaleString('zh-TW'),customer,phone,status:'待確認',total,items:state.cart.map(({id,name,price,qty})=>({id,name,price,qty}))});state.cart=[];state.modal=null;state.view='orders';save();render();toast('訂單已送出，謝謝你！')});document.querySelector('[data-action="export"]')?.addEventListener('click',exportCsv)}
render();
