import { createRequire } from 'node:module';
import { readFile, mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import assert from 'node:assert/strict';
const { chromium } = createRequire(import.meta.url)('playwright');
const source = await readFile(new URL('../profit-sharing.js', import.meta.url), 'utf8');
const css = (await readFile(new URL('../styles.css', import.meta.url), 'utf8')).replace(/^@import[^\r\n]+\r?\n/, '');
const output = await mkdtemp(join(tmpdir(), 'newshop-zero-cost-'));
const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  for (const width of [1366, 390, 320]) {
    const page = await browser.newPage({ viewport: { width, height: 844 } });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.route('http://localhost/zero-test', route => route.fulfill({ contentType: 'text/html', body: `<meta charset="utf-8"><style>${css}</style><div id="fixture" style="padding:16px"></div>` }));
    await page.goto('http://localhost/zero-test');
    await page.evaluate(async source => {
      const { createProfitSharing, calculateProfitShare } = await import(URL.createObjectURL(new Blob([source], { type: 'text/javascript' })));
      const products = [{ id:'p1', name:'零成本商品 <一>' }, { id:'p2', name:'混合成本商品' }, { id:'p3', name:'有成本商品' }];
      const items = [{ id:'a', product_id:'p1', product_name:products[0].name, quantity:2, unit_price:200, unit_cost:0 }, { id:'b', product_id:'p2', product_name:products[1].name, quantity:1, unit_price:300, unit_cost:0 }, { id:'b2', product_id:'p2', product_name:products[1].name, quantity:1, unit_price:300, unit_cost:100 }, { id:'c', product_id:'p3', product_name:products[2].name, quantity:1, unit_price:500, unit_cost:200 }];
      const state = { user:{id:'admin'}, profile:{role:'owner'}, markets:[{id:'m1',name:'測試賣場',products}], products, orders:[{id:'o1',recipient_name:'買家',status:'confirmed',order_items:items}], fulfillmentChecks:new Map(items.map(item=>[item.id,{shipped_at:'2026-10-01',completed_at:'2026-10-02',reconciled_at:'2026-10-02'}])) };
      let controller;
      const records = [];
      const supabase = { from:()=>({select:()=>({order:async()=>({data:structuredClone(records)})})}), rpc:async(name,args)=>{
        window.savedIds = args.p_item_ids;
        const snapshot = calculateProfitShare(args.p_settings.expected_items, args.p_settings);
        const data = {id:'saved',completed_at:new Date().toISOString(),snapshot}; records.push(data); return {data};
      }};
      const esc = value => String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[ch]);
      const render = () => { document.querySelector('#fixture').innerHTML = controller.panel() + (state.modal ? controller.modal() : ''); controller.bind(); };
      controller = createProfitSharing({ state, supabase, esc, money:value=>`NT$ ${Number(value).toLocaleString('zh-TW')}`, getCost:item=>item.unit_cost, render, toast:message=>window.lastToast=message, reload:async()=>{}, bindBackdropClose:(element,close)=>element.addEventListener('click',event=>{if(event.target===element)close();}) });
      await controller.load(); render(); window.zeroFixture={state,render};
    }, source);
    await page.locator('[data-profit-market]').check();
    await page.locator('[data-profit-next]').click();
    assert.equal(await page.locator('[data-profit-zero-product]').count(),2,'Warn even when only some order lines of a product have zero cost');
    assert.equal(await page.locator('[data-profit-zero-product]:checked').count(),0,'Confirmation must be explicit');
    assert.equal(await page.locator('[data-profit-title]').count(),0);
    assert.match(await page.locator('.profit-zero-list').textContent(),/零成本商品 <一>/);
    assert.equal(await page.locator('.profit-zero-list script').count(),0);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.locator('.profit-zero-cost-modal').evaluate(el=>Promise.all(el.getAnimations().map(animation=>animation.finished)));
    await page.screenshot({path:join(output,`warning-${width}.png`),fullPage:true});
    await page.locator('[data-profit-zero-close]').last().click();
    assert.equal(await page.locator('[data-profit-product]:checked').count(),3,'Cancel leaves selection unchanged');
    await page.locator('[data-profit-next]').click();
    await page.locator('[data-profit-zero-product="p1"]').check();
    await page.locator('[data-profit-zero-confirm]').click();
    assert.equal(await page.locator('[data-profit-product-payer="p2"]').count(),0);
    assert.equal(await page.locator('[data-profit-product-payer]').count(),2,'Keep confirmed zero cost and nonzero cost products');
    assert.equal(await page.locator('[data-profit-received]').inputValue(),'900','Exclude rejected product from amount');
    await page.locator('[data-profit-back="select"]').click();
    await page.locator('[data-profit-product="p3"]').uncheck();
    await page.locator('[data-profit-next]').click();
    await page.locator('[data-profit-zero-confirm]').click();
    assert.equal(await page.locator('[data-profit-title]').count(),0,'All rejected stays in selection');
    assert.equal(await page.locator('[data-profit-next]').isDisabled(),true);
    await page.locator('[data-profit-product="p3"]').check();
    await page.locator('[data-profit-next]').click();
    assert.equal(await page.locator('.profit-zero-cost-modal').count(),0,'Nonzero-only selection proceeds directly');
    await page.locator('[data-profit-back="select"]').click();
    await page.locator('[data-profit-market]').check();
    await page.locator('[data-profit-next]').click();
    await page.locator('[data-profit-zero-product="p1"]').check();
    await page.locator('[data-profit-zero-confirm]').click();
    await page.locator('[data-profit-confirmed]').check();
    await page.locator('[data-profit-calculate]').click();
    assert.equal(await page.locator('.profit-result-items [data-profit-product-row="p2"]').count(),0);
    assert.match(await page.locator('.profit-totals').textContent(),/可分利潤NT\$ 700/);
    await page.locator('[data-profit-finish]').click();
    await page.locator('[data-profit-history]').waitFor();
    assert.deepEqual(await page.evaluate(()=>window.savedIds),['a','c'],'Excluded order lines never reach SQL request');
    assert.equal(await page.evaluate(()=>window.zeroFixture.state.orders[0].order_items.length),4,'No orders removed');
    assert.deepEqual(errors,[]);
    console.log(`PASS ${width}px: zero-cost warning, explicit selection, mixed costs, cancellation, empty selection, filtered amounts and save`);
    await page.close();
  }
  console.log(`Screenshots: ${output}`);
} finally { await browser.close(); }
